---
title: "Default of Credit Cards"
output:
  html_document:
    toc: yes
    keep_md: yes
  pdf_document:
    toc: yes
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(kableExtra)
library(tidyverse)
```

## Data 

- https://www.kaggle.com/datasets/uciml/default-of-credit-card-clients-dataset 

## Preprocessing 

- BP_R*
- CB_*

## EDA

#### Target class distributions 

```{r load data, include = FALSE}
train_target_class_dis <- read_csv('../results/eda/train_target_class_dis.csv', show_col_types = FALSE)
test_target_class_dis <- read_csv('../results/eda/test_target_class_dis.csv', show_col_types = FALSE) 
```

```{r table 1}
knitr::kable(train_target_class_dis, caption = "Table 1. Target Class Distribution in Training Set") %>%
kableExtra::kable_styling(full_width = TRUE)
```

```{r table 2}
knitr::kable(test_target_class_dis, caption = "Table 2. Target Class Distribution in Test Set") %>%
kableExtra::kable_styling(full_width = TRUE)
```